# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_advertisement_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='advertisement',
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
